// AUTO-GENERATED by scripts/sync-tokens.mjs — edits will be overwritten.
// Run `node scripts/sync-tokens.mjs` to regenerate.
//
// ignore_for_file: constant_identifier_names
// Snake_case constant names mirror the shared token JSON keys
// (spacing_card, radius_xl, …) one-to-one. Renaming to camelCase
// would break the source-of-truth contract documented in
// shared/README.md.
import 'package:flutter/material.dart';

class AppGeneratedTokens {
  AppGeneratedTokens._();

  static const Color primary_50 = Color(0xFFEFF6FF);
  static const Color primary_100 = Color(0xFFDBEAFE);
  static const Color primary_200 = Color(0xFFBFDBFE);
  static const Color primary_300 = Color(0xFF93C5FD);
  static const Color primary_400 = Color(0xFF60A5FA);
  static const Color primary_500 = Color(0xFF2563EB);
  static const Color primary_600 = Color(0xFF2451CC);
  static const Color primary_700 = Color(0xFF1D4ED8);
  static const Color primary_800 = Color(0xFF1E40AF);
  static const Color primary_900 = Color(0xFF1E3A8A);
  static const Color accent_50 = Color(0xFFFEF2F2);
  static const Color accent_100 = Color(0xFFFEE2E2);
  static const Color accent_500 = Color(0xFFDC2626);
  static const Color accent_600 = Color(0xFFB91C1C);
  static const Color accent_700 = Color(0xFF991B1B);
  static const Color success_50 = Color(0xFFECFDF5);
  static const Color success_100 = Color(0xFFDCFCE7);
  static const Color success_500 = Color(0xFF16A34A);
  static const Color success_600 = Color(0xFF059669);
  static const Color success_700 = Color(0xFF047857);
  static const Color warning_50 = Color(0xFFFFFBEB);
  static const Color warning_100 = Color(0xFFFEF3C7);
  static const Color warning_500 = Color(0xFFF59E0B);
  static const Color warning_600 = Color(0xFFD97706);
  static const Color warning_700 = Color(0xFF92400E);
  static const Color info_100 = Color(0xFFCFFAFE);
  static const Color info_500 = Color(0xFF06B6D4);
  static const Color info_600 = Color(0xFF0891B2);
  static const Color neutral_surface = Color(0xFFFFFFFF);
  static const Color neutral_surface_alt = Color(0xFFF8FAFC);
  static const Color neutral_surface_muted = Color(0xFFF1F5F9);
  static const Color neutral_border = Color(0xFFE2E8F0);
  static const Color dark_bg = Color(0xFF0F172A);
  static const Color dark_bg_alt = Color(0xFF1A2538);
  static const Color dark_card = Color(0xFF1E293B);
  static const Color dark_border = Color(0xFF334155);
  static const Color dark_text = Color(0xFFE2E8F0);
  static const Color dark_muted = Color(0xFF94A3B8);

  static const double spacing_0 = 0.0;
  static const double spacing_1 = 4.0;
  static const double spacing_2 = 8.0;
  static const double spacing_3 = 12.0;
  static const double spacing_4 = 16.0;
  static const double spacing_5 = 20.0;
  static const double spacing_6 = 24.0;
  static const double spacing_8 = 32.0;
  static const double spacing_10 = 40.0;
  static const double spacing_12 = 48.0;
  static const double spacing_16 = 64.0;
  static const double spacing_20 = 80.0;
  static const double spacing_24 = 96.0;
  static const double spacing_px = 1.0;
  static const double spacing_0_5 = 2.0;
  static const double spacing_1_5 = 6.0;
  static const double spacing_card = 20.0;
  static const double spacing_section = 28.0;

  static const double radius_none = 0.0;
  static const double radius_sm = 6.0;
  static const double radius_md = 10.0;
  static const double radius_lg = 14.0;
  static const double radius_xl = 18.0;
  static const double radius_2xl = 22.0;
  static const double radius_3xl = 28.0;
  static const double radius_pill = 9999.0;

  static const Duration durationFast   = Duration(milliseconds: 140);
  static const Duration durationNormal = Duration(milliseconds: 220);
  static const Duration durationSlow   = Duration(milliseconds: 420);
}
