#!/usr/bin/env node
// @ts-check
/**
 * Reads the canonical JSON token files in `shared/tokens/*.json` and rewrites the
 * platform-specific files that consume them. Run after editing any token file.
 *
 *   node scripts/sync-tokens.mjs
 *
 * Generated outputs:
 *   - shared/tokens/dist/tokens.ts        — typed const for any TS consumer
 *   - mobile/src/lib/generated-tokens.ts  — Expo/RN ad-hoc styles
 *   - flutter/lib/app/theme/app_generated_tokens.dart — Dart static class
 *   - web/src/lib/generated-tokens.ts     — Next.js consumers
 *
 * NB: We don't auto-edit the Tailwind/CSS sources — those have hand-written annotations and
 * @utility blocks that would be lossy to round-trip. Instead each platform's hand-authored
 * theme can import from the generated TS/Dart constants when it needs the raw values.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const tokensDir = join(root, "shared", "tokens");

const colors  = JSON.parse(readFileSync(join(tokensDir, "colors.json"),  "utf8"));
const spacing = JSON.parse(readFileSync(join(tokensDir, "spacing.json"), "utf8"));
const radius  = JSON.parse(readFileSync(join(tokensDir, "radius.json"),  "utf8"));
const motion  = JSON.parse(readFileSync(join(tokensDir, "motion.json"),  "utf8"));

/** Pull the leaf `value` from a Design-Token-Format node, recursively. */
function leaves(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object" && "value" in v) {
      out[k] = v.value;
    } else if (v && typeof v === "object") {
      out[k] = leaves(v);
    }
  }
  return out;
}

const palette = leaves(colors);
const spaces  = leaves(spacing);
const radii   = leaves(radius);
const motions = leaves(motion);

mkdirSync(join(tokensDir, "dist"), { recursive: true });

// ─── shared TS ────────────────────────────────────────────
const tsHeader = `// AUTO-GENERATED by scripts/sync-tokens.mjs — edits will be overwritten.
// Run \`node scripts/sync-tokens.mjs\` to regenerate.
`;
const tsBody = `${tsHeader}
export const palette = ${JSON.stringify(palette, null, 2)} as const;
export const spacing = ${JSON.stringify(spaces,  null, 2)} as const;
export const radius  = ${JSON.stringify(radii,   null, 2)} as const;
export const motion  = ${JSON.stringify(motions, null, 2)} as const;
`;

writeFileSync(join(tokensDir, "dist", "tokens.ts"), tsBody);
mkdirSync(join(root, "mobile", "src", "lib"), { recursive: true });
mkdirSync(join(root, "web", "src", "lib"),   { recursive: true });
writeFileSync(join(root, "mobile", "src", "lib", "generated-tokens.ts"), tsBody);
writeFileSync(join(root, "web",    "src", "lib", "generated-tokens.ts"), tsBody);

// ─── Dart ─────────────────────────────────────────────────
function dartColorEntries(obj, prefix = "") {
  const lines = [];
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "string") {
      const hex = v.replace(/^#/, "").toUpperCase();
      const argb = hex.length === 6 ? "FF" + hex : hex;
      const name = (prefix + k).replace(/[^A-Za-z0-9]/g, "_");
      lines.push(`  static const Color ${name} = Color(0x${argb});`);
    } else if (v && typeof v === "object") {
      lines.push(...dartColorEntries(v, prefix + k + "_"));
    }
  }
  return lines;
}

function dartNumberEntries(obj, prefix, type = "double") {
  const lines = [];
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "number") {
      const name = (prefix + k).replace(/[^A-Za-z0-9]/g, "_");
      lines.push(`  static const ${type} ${name} = ${type === "int" ? v : v.toFixed(1)};`);
    }
  }
  return lines;
}

const dart = `// AUTO-GENERATED by scripts/sync-tokens.mjs — edits will be overwritten.
// Run \`node scripts/sync-tokens.mjs\` to regenerate.
import 'package:flutter/material.dart';

class AppGeneratedTokens {
  AppGeneratedTokens._();

${dartColorEntries(palette).join("\n")}

${dartNumberEntries(spaces, "spacing_").join("\n")}

${dartNumberEntries(radii, "radius_").join("\n")}

  static const Duration durationFast   = Duration(milliseconds: ${motions.duration.fast});
  static const Duration durationNormal = Duration(milliseconds: ${motions.duration.normal});
  static const Duration durationSlow   = Duration(milliseconds: ${motions.duration.slow});
}
`;
mkdirSync(join(root, "flutter", "lib", "app", "theme"), { recursive: true });
writeFileSync(
  join(root, "flutter", "lib", "app", "theme", "app_generated_tokens.dart"),
  dart,
);

console.log("✓ tokens regenerated");
console.log("  • shared/tokens/dist/tokens.ts");
console.log("  • mobile/src/lib/generated-tokens.ts");
console.log("  • web/src/lib/generated-tokens.ts");
console.log("  • flutter/lib/app/theme/app_generated_tokens.dart");
