// AUTO-GENERATED by scripts/sync-tokens.mjs — edits will be overwritten.
// Run `node scripts/sync-tokens.mjs` to regenerate.

export const palette = {
  "primary": {
    "50": "#eff6ff",
    "100": "#dbeafe",
    "200": "#bfdbfe",
    "300": "#93c5fd",
    "400": "#60a5fa",
    "500": "#2563EB",
    "600": "#2451cc",
    "700": "#1d4ed8",
    "800": "#1e40af",
    "900": "#1e3a8a"
  },
  "accent": {
    "50": "#fef2f2",
    "100": "#fee2e2",
    "500": "#DC2626",
    "600": "#b91c1c",
    "700": "#991b1b"
  },
  "success": {
    "50": "#ecfdf5",
    "100": "#dcfce7",
    "500": "#16a34a",
    "600": "#059669",
    "700": "#047857"
  },
  "warning": {
    "50": "#fffbeb",
    "100": "#fef3c7",
    "500": "#f59e0b",
    "600": "#d97706",
    "700": "#92400e"
  },
  "info": {
    "100": "#cffafe",
    "500": "#06b6d4",
    "600": "#0891b2"
  },
  "neutral": {
    "surface": "#ffffff",
    "surface-alt": "#f8fafc",
    "surface-muted": "#f1f5f9",
    "border": "#e2e8f0"
  },
  "dark": {
    "bg": "#0f172a",
    "bg-alt": "#1a2538",
    "card": "#1e293b",
    "border": "#334155",
    "text": "#e2e8f0",
    "muted": "#94a3b8"
  }
} as const;
export const spacing = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40,
  "12": 48,
  "16": 64,
  "20": 80,
  "24": 96,
  "px": 1,
  "0.5": 2,
  "1.5": 6,
  "card": 20,
  "section": 28
} as const;
export const radius  = {
  "none": 0,
  "sm": 6,
  "md": 10,
  "lg": 14,
  "xl": 18,
  "2xl": 22,
  "3xl": 28,
  "pill": 9999
} as const;
export const motion  = {
  "duration": {
    "fast": 140,
    "normal": 220,
    "slow": 420
  },
  "easing": {
    "out-quad": [
      0.25,
      0.46,
      0.45,
      0.94
    ],
    "out-expo": [
      0.16,
      1,
      0.3,
      1
    ],
    "spring": [
      0.34,
      1.56,
      0.64,
      1
    ]
  }
} as const;
