import type { Profile, Job, Application, Education, Experience, LanguageSkill, Document } from "../types";

export const mockProfiles: Profile[] = [
  {
    id: "p1",
    user_id: "u1",
    role: "applicant",
    first_name: "Ahmed",
    last_name: "Ben Ali",
    photo_url: null,
    phone: "+216 55 123 456",
    city: "Tunis",
    country: "Tunesien",
    bio: "IT-Fachkraft mit 5 Jahren Erfahrung in Webentwicklung. Suche eine Stelle in Deutschland.",
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    user_id: "u2",
    role: "employer",
    first_name: "Deutsche",
    last_name: "Pflegedienst GmbH",
    photo_url: null,
    phone: "+49 30 123 456",
    city: "Berlin",
    country: "Deutschland",
    bio: "Pflegedienst mit 200+ Mitarbeitern in Berlin und Brandenburg.",
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    user_id: "u3",
    role: "employer",
    first_name: "TechStart",
    last_name: "Solutions AG",
    photo_url: null,
    phone: "+49 89 987 654",
    city: "M\u00fcnchen",
    country: "Deutschland",
    bio: "Software-Unternehmen spezialisiert auf Cloud-L\u00f6sungen.",
    created_at: new Date().toISOString(),
  },
  {
    id: "p4",
    user_id: "u4",
    role: "admin",
    first_name: "Admin",
    last_name: "bewerbi.tn",
    photo_url: null,
    phone: "",
    city: "Tunis",
    country: "Tunesien",
    bio: "",
    created_at: new Date().toISOString(),
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    employer_id: "p3",
    title: "Full-Stack Entwickler (m/w/d)",
    description: "Wir suchen einen erfahrenen Full-Stack Entwickler f\u00fcr unser Team in M\u00fcnchen. Du arbeitest an innovativen Cloud-L\u00f6sungen mit React, Node.js und AWS.\n\nAufgaben:\n- Entwicklung von Web-Applikationen\n- API-Design und Implementierung\n- Code Reviews und Mentoring\n- Agile Zusammenarbeit im Team",
    category: "it",
    type: "job",
    location: "M\u00fcnchen",
    requirements: "- 3+ Jahre Erfahrung in React/TypeScript\n- Node.js und REST APIs\n- Deutsch B2 oder h\u00f6her\n- Abgeschlossenes Studium in Informatik",
    salary_range: "55.000 - 75.000 \u20ac",
    german_level: "B2",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[2],
  },
  {
    id: "j2",
    employer_id: "p2",
    title: "Pflegefachkraft (m/w/d)",
    description: "Zur Verst\u00e4rkung unseres Teams suchen wir eine examinierte Pflegefachkraft f\u00fcr die ambulante Pflege in Berlin.\n\nWir bieten:\n- Unbefristeter Vertrag\n- Unterst\u00fctzung bei Visa und Anerkennung\n- Sprachkurs-F\u00f6rderung\n- Willkommenspaket f\u00fcr internationale Kr\u00e4fte",
    category: "pflege",
    type: "job",
    location: "Berlin",
    requirements: "- Abgeschlossene Pflegeausbildung\n- Bereitschaft zum Schichtdienst\n- Deutsch B1\n- F\u00fchrerschein Klasse B von Vorteil",
    salary_range: "38.000 - 48.000 \u20ac",
    german_level: "B1",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[1],
  },
  {
    id: "j3",
    employer_id: "p2",
    title: "Ausbildung zur Pflegefachkraft",
    description: "Starte deine Karriere in der Pflege mit einer 3-j\u00e4hrigen Ausbildung in unserem Betrieb.\n\nDie Ausbildung umfasst:\n- Theorie und Praxis\n- Begleiteter Deutschkurs\n- Ausbildungsverg\u00fctung ab dem 1. Tag\n- \u00dcbernahme nach erfolgreichem Abschluss",
    category: "pflege",
    type: "ausbildung",
    location: "Berlin",
    requirements: "- Mittlerer Schulabschluss\n- Deutsch A2 (B1 wird w\u00e4hrend der Ausbildung erreicht)\n- Motivation und Empathie",
    salary_range: "1.200 - 1.500 \u20ac/Monat",
    german_level: "A2",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[1],
  },
  {
    id: "j4",
    employer_id: "p3",
    title: "LKW-Fahrer CE (m/w/d)",
    description: "F\u00fcr unseren Logistikpartner suchen wir erfahrene LKW-Fahrer f\u00fcr den nationalen und internationalen Fernverkehr.\n\nBenefits:\n- Moderner Fuhrpark\n- Faire Spesen\n- Regelm\u00e4\u00dfige Heimfahrten",
    category: "transport",
    type: "job",
    location: "Hamburg",
    requirements: "- F\u00fchrerschein CE + Module\n- 2+ Jahre Berufserfahrung\n- Deutsch A2\n- ADR-Schein von Vorteil",
    salary_range: "35.000 - 45.000 \u20ac",
    german_level: "A2",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[2],
  },
  {
    id: "j5",
    employer_id: "p3",
    title: "Intensiv-Deutschkurs B1 in Berlin",
    description: "12-w\u00f6chiger Intensiv-Deutschkurs f\u00fcr Fachkr\u00e4fte, die nach Deutschland auswandern m\u00f6chten.\n\nKursinhalt:\n- 20 Stunden/Woche\n- Pr\u00fcfungsvorbereitung Goethe B1\n- Berufsbezogenes Deutsch\n- Kulturelle Orientierung",
    category: "sonstige",
    type: "sprachkurs",
    location: "Online + Berlin",
    requirements: "- Deutsch A2 Vorkenntnisse\n- Internetzugang f\u00fcr Online-Sessions",
    salary_range: "1.800 \u20ac (Kurs)",
    german_level: "A2",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[2],
  },
  {
    id: "j6",
    employer_id: "p3",
    title: "Informatik Studium - TU M\u00fcnchen",
    description: "Bachelor-Studiengang Informatik an der TU M\u00fcnchen f\u00fcr internationale Studierende.\n\nHighlights:\n- Englischsprachige Module verf\u00fcgbar\n- Stipendien-Programm\n- Studentenwohnheim\n- Praxissemester bei Partnerunternehmen",
    category: "it",
    type: "studium",
    location: "M\u00fcnchen",
    requirements: "- Abitur oder \u00e4quivalent\n- Deutsch B2 oder Englisch C1\n- Mathematik-Grundkenntnisse\n- Motivationsschreiben",
    salary_range: null,
    german_level: "B2",
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[2],
  },
  {
    id: "j7",
    employer_id: "p3",
    title: "DevOps Engineer (m/w/d)",
    description: "Wir suchen einen DevOps Engineer zur Automatisierung unserer CI/CD-Pipelines und Cloud-Infrastruktur.\n\nTech Stack:\n- Kubernetes, Docker\n- Terraform, Ansible\n- AWS/GCP\n- GitLab CI",
    category: "it",
    type: "job",
    location: "Frankfurt",
    requirements: "- 2+ Jahre DevOps Erfahrung\n- Kubernetes & Docker\n- CI/CD Pipelines\n- Linux Administration\n- Deutsch B1",
    salary_range: "60.000 - 80.000 \u20ac",
    german_level: "B1",
    created_at: new Date().toISOString(),
    status: "active",
    employer: mockProfiles[2],
  },
  {
    id: "j8",
    employer_id: "p2",
    title: "Busfahrer (m/w/d) - \u00d6PNV",
    description: "F\u00fcr den \u00f6ffentlichen Nahverkehr in K\u00f6ln suchen wir zuverl\u00e4ssige Busfahrer.\n\nWir bieten:\n- Tarifvertrag \u00d6PNV\n- 30 Tage Urlaub\n- Jobticket\n- Unterst\u00fctzung beim Umzug",
    category: "transport",
    type: "job",
    location: "K\u00f6ln",
    requirements: "- F\u00fchrerschein D + Personenbef\u00f6rderungsschein\n- Deutsch B1\n- Kundenorientierung\n- Zuverl\u00e4ssigkeit",
    salary_range: "32.000 - 40.000 \u20ac",
    german_level: "B1",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    employer: mockProfiles[1],
  },
];

export const mockEducation: Education[] = [
  {
    id: "e1",
    profile_id: "p1",
    degree: "Licence (Bachelor)",
    institution: "Universit\u00e9 de Tunis El Manar",
    field_of_study: "Informatik",
    country: "Tunesien",
    start_date: "2016-09",
    end_date: "2019-06",
  },
  {
    id: "e2",
    profile_id: "p1",
    degree: "Mast\u00e8re (Master)",
    institution: "ENIT - \u00c9cole Nationale d'Ing\u00e9nieurs de Tunis",
    field_of_study: "Software Engineering",
    country: "Tunesien",
    start_date: "2019-09",
    end_date: "2021-06",
  },
];

export const mockExperience: Experience[] = [
  {
    id: "ex1",
    profile_id: "p1",
    job_title: "Junior Web Developer",
    company: "Vermeg",
    location: "Tunis, Tunesien",
    start_date: "2021-07",
    end_date: "2023-03",
    description: "Entwicklung von Bankanwendungen mit Angular und Spring Boot.",
  },
  {
    id: "ex2",
    profile_id: "p1",
    job_title: "Full-Stack Developer",
    company: "Sofrecom Tunisia",
    location: "Tunis, Tunesien",
    start_date: "2023-04",
    end_date: null,
    description: "React/Node.js Entwicklung f\u00fcr Telekommunikationskunden.",
  },
];

export const mockLanguages: LanguageSkill[] = [
  { id: "l1", profile_id: "p1", language: "Arabisch", level: "C2" },
  { id: "l2", profile_id: "p1", language: "Franz\u00f6sisch", level: "C1" },
  { id: "l3", profile_id: "p1", language: "Deutsch", level: "B1" },
  { id: "l4", profile_id: "p1", language: "Englisch", level: "B2" },
];

export const mockDocuments: Document[] = [
  {
    id: "d1",
    profile_id: "p1",
    type: "cv",
    file_url: "https://example.com/cv.pdf",
    name: "Lebenslauf_Ahmed_BenAli.pdf",
    created_at: new Date().toISOString(),
  },
  {
    id: "d2",
    profile_id: "p1",
    type: "diploma",
    file_url: "https://example.com/diploma.pdf",
    name: "Master_Diplom_ENIT.pdf",
    created_at: new Date().toISOString(),
  },
];

export const mockApplications: Application[] = [
  {
    id: "a1",
    job_id: "j1",
    applicant_id: "p1",
    status: "reviewed",
    cover_letter: "Sehr geehrte Damen und Herren, ich bewerbe mich auf die Stelle als Full-Stack Entwickler...",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
    applicant: mockProfiles[0],
  },
  {
    id: "a2",
    job_id: "j7",
    applicant_id: "p1",
    status: "pending",
    cover_letter: "Mit gro\u00dfem Interesse bewerbe ich mich als DevOps Engineer...",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[6],
    applicant: mockProfiles[0],
  },
];
